In [ ]:
import torch


tensor = torch.arange(1, 101).view(10, 10)
print(tensor)

tensor_T = tensor.transpose(0, 1)
print(tensor_T.data_ptr() == tensor.data_ptr()) 


submatrix = tensor[1:, 1:]
size = submatrix.size()
stride = submatrix.stride()
offset = submatrix.storage_offset()
print("Size:", size)     
print("Stride:", stride) 
print("Offset:", offset) 


tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])
True
Size: torch.Size([9, 9])
Stride: (10, 1)
Offset: 11


In [2]:
A = torch.randn(10, 10)
q, r = torch.qr(A)
A = q

C:\Users\fares\AppData\Local\Temp\ipykernel_19172\2423783139.py:2: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:2431.)
  q, r = torch.qr(A)


In [3]:
print("Ausgangsmatrix A:")
print(A)

Ausgangsmatrix A:
tensor([[-0.2278, -0.2188,  0.2264, -0.0700, -0.2581,  0.7958,  0.0049, -0.2017,
         -0.2996,  0.1167],
        [-0.3910, -0.1328,  0.3194,  0.2903, -0.0348,  0.0899, -0.0351,  0.7027,
          0.3719,  0.0232],
        [ 0.1618, -0.5901, -0.4894,  0.2474, -0.2471,  0.0373,  0.2019,  0.1458,
         -0.0745, -0.4415],
        [ 0.1948, -0.1336,  0.0456, -0.3142, -0.6569, -0.1142,  0.1338, -0.1032,
          0.5168,  0.3212],
        [ 0.2104,  0.2437, -0.3023, -0.0275, -0.1483,  0.3006, -0.7785,  0.1252,
          0.2034, -0.1696],
        [-0.2219, -0.0684,  0.1994,  0.5069, -0.0190, -0.0745, -0.1443, -0.6330,
          0.3906, -0.2634],
        [ 0.1086, -0.4587,  0.5044, -0.4520,  0.0937, -0.2238, -0.3404,  0.0074,
         -0.0902, -0.3689],
        [ 0.3713,  0.4020,  0.2790, -0.0741,  0.0017,  0.3061,  0.4233,  0.0765,
          0.2076, -0.5434],
        [ 0.5143,  0.0472,  0.3765,  0.5241, -0.3010, -0.1429, -0.1335,  0.0969,
         -0.3762,  0.1927],
 

In [4]:
A_inv = torch.inverse(A)

print("Inverse Matrix A^-1:")
print(A_inv)

Inverse Matrix A^-1:
tensor([[-0.2278, -0.3910,  0.1618,  0.1948,  0.2104, -0.2219,  0.1086,  0.3713,
          0.5143,  0.4727],
        [-0.2188, -0.1328, -0.5901, -0.1336,  0.2437, -0.0684, -0.4587,  0.4020,
          0.0472, -0.3607],
        [ 0.2264,  0.3194, -0.4894,  0.0456, -0.3023,  0.1994,  0.5044,  0.2790,
          0.3765,  0.0055],
        [-0.0700,  0.2903,  0.2474, -0.3142, -0.0275,  0.5069, -0.4520, -0.0741,
          0.5241,  0.0932],
        [-0.2581, -0.0348, -0.2471, -0.6569, -0.1483, -0.0190,  0.0937,  0.0017,
         -0.3010,  0.5637],
        [ 0.7958,  0.0899,  0.0373, -0.1142,  0.3006, -0.0745, -0.2238,  0.3061,
         -0.1429,  0.2898],
        [ 0.0049, -0.0351,  0.2019,  0.1338, -0.7785, -0.1443, -0.3404,  0.4233,
         -0.1335,  0.0189],
        [-0.2017,  0.7027,  0.1458, -0.1032,  0.1252, -0.6330,  0.0074,  0.0765,
          0.0969, -0.0434],
        [-0.2996,  0.3719, -0.0745,  0.5168,  0.2034,  0.3906, -0.0902,  0.2076,
         -0.3762,  0.3356]

In [5]:
I = torch.matmul(A, A_inv)
print("Produkt von A und A^-1:")
print(I)

Produkt von A und A^-1:
tensor([[ 1.0000e+00,  1.0425e-08,  1.6686e-08, -4.6406e-08, -4.4197e-08,
          1.3037e-08, -7.2153e-08, -2.6206e-08,  8.3493e-08,  3.0099e-08],
        [ 1.3451e-08,  1.0000e+00,  1.3129e-08, -2.0737e-08,  2.3598e-08,
          8.7550e-09, -8.4845e-08,  9.0149e-09,  1.1346e-08,  3.0616e-08],
        [-4.4660e-09,  2.4384e-09,  1.0000e+00, -3.5991e-09, -1.0906e-08,
         -9.6313e-09,  4.0012e-08,  2.9641e-09, -2.4025e-08, -4.0134e-08],
        [-2.6963e-08, -1.0108e-07,  4.5674e-08,  1.0000e+00, -4.7734e-08,
         -1.1045e-08,  6.6980e-08,  9.4647e-09, -3.5372e-08, -3.7496e-08],
        [-2.3243e-08, -1.8740e-08, -1.8970e-08,  1.3465e-08,  1.0000e+00,
         -1.6437e-08,  5.1153e-08,  4.3833e-08, -7.0614e-09, -1.3955e-08],
        [-1.6198e-08,  3.5927e-08,  4.3719e-08, -3.2599e-08,  4.2969e-08,
          1.0000e+00, -1.1849e-07,  4.1281e-08,  9.4703e-08, -9.6202e-09],
        [-2.5179e-08, -2.4733e-08,  1.1246e-07,  1.5541e-08, -1.3690e-08,
        

In [9]:
from PIL import Image
import numpy as np


image = Image.open(r"C:\Users\fares\Downloads\cat.jpg")
image_array = np.array(image)

In [18]:
import numpy as np
from PIL import Image
from numpy.lib.stride_tricks import as_strided


image = Image.open(r"C:\Users\fares\Downloads\cat.jpg")


image_arr = np.array(image)


size = (int(image_arr.shape[0] / 2), int(image_arr.shape[1] / 2))


strides = tuple([stride*2 for stride in image_arr.strides])

cutout = as_strided(image_arr, shape=size + image_arr.shape[2:], strides=strides)


cutout_image = Image.fromarray(cutout)
cutout_image.save("cutout.jpg")

In [19]:
cutout_image.show()